apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymonitor-expense-reports
spec:
  template:
    spec:
      containers:
        - name: paymonitor-expense-reports
          env:
            - name: DOTNET_gcServer
              value: "0"
            - name: DOTNET_GCHeapHardLimit
              value: "476837000"