import type { SheriffConfig } from '@softarc/sheriff-core';

import { noDependencies, sameTag } from '@softarc/sheriff-core';

export const sheriffConfig: SheriffConfig = {
  entryFile: './src/main.ts',
  version: 1,
  tagging: {
    'src/app': {
      'app.ts': ['root'],
      'app.config.ts': ['root'],
      'app.routes.ts': ['root'],
      'app.html': ['root'],
      'domains/<domain>': {
        feature: ['domain:<domain>', 'type:feature'],
        ui: ['domain:<domain>', 'type:ui'],
        data: ['domain:<domain>', 'type:data'],
        util: ['domain:<domain>', 'type:util'],
        'autogenerated/models': ['domain:<domain>', 'type:util'],
        'autogenerated/services': ['domain:<domain>', 'type:data'],
      },
    },
  },
  enableBarrelLess: true,
  depRules: {
    // Règle 1: On ne peut importer que ce qui est dans le même domaine ou 'shared'
    'domain:*': [sameTag, 'domain:shared'],

    // Règle 2: La hiérarchie des couches (Feature > UI > Data > Util)
    'type:feature': ['type:ui', 'type:data', 'type:util'],
    'type:ui': ['type:data', 'type:util'], // UI ne peut pas voir Feature
    'type:data': ['type:util'], // Data ne voit que Util
    'type:util': noDependencies, // Util ne dépend de personne

    // Le root (bootstrap) peut tout importer
    root: ['type:feature', 'type:ui', 'type:data', 'type:util', 'domain:shared'],
  },
};
